sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4_2.gemfile
