sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.1

gemfile:
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_2.gemfile
